// categories.js
export const categories = [
  'Personality and Traits',
  'Food and Drink',
  'Music, Movies, and TV Shows',
  'Travel and Adventure',
  'Conversation Style and Humor',
  'Mindset and Lifestyle',
  'Random Fun Cards'
];

export const traits = {
  'Personality and Traits': [
    'Introvert vs. Extrovert',
    'Optimistic vs. Realist',
    'Adventurous vs. Homebody',
    'Morning person vs. Night owl',
    'Spontaneous vs. Planner',
    'Organized vs. Messy',
    'Empathic vs. Logical',
    'Risk-taker vs. Cautious',
    'Sentimental vs. Pragmatic',
    'Glass half full vs. Glass half empty',
  ],
  'Food and Drink': [
    'Sweet tooth vs. Salty snacks lover',
    'Vegetarian vs. Meat lover',
    'Coffee addict vs. Tea enthusiast',
    'Spicy food lover vs. Mild food lover',
    'Cooking a 5-course meal vs. Order takeout every time',
    'Late-night snacks vs. Meal preppers',
    'Wine enthusiast vs. Beer lover',
    'Smoothie fan vs. Juice lover',
    'Cook with recipes vs. Cook by feeling',
    'Dessert first vs. Appetizer first',
  ],
  'Music, Movies, and TV Shows': [
    'Pop music lover vs. Rock music lover',
    'Into indie music vs. Mainstream hits',
    'Horror movie fan vs. Comedy movie fan',
    'Reality TV fan vs. Documentary lover',
    'Love musicals vs. Prefer action-packed films',
    'Binge-watching series vs. Slow and steady watcher',
    'Spotify playlists vs. Vinyl records',
    'Sci-fi TV shows vs. True crime shows',
    'Classic movies vs. Modern blockbusters',
    'Concert-goer vs. Stay-at-home listener',
  ],
  'Travel and Adventure': [
    'Beach vacation vs. Mountain retreat',
    'Wants to visit Paris vs. Wants to visit Tokyo',
    'Road trips vs. Flight to a destination',
    'Solo travel vs. Travel with friends',
    'Loves hiking vs. Loves city tours',
    'Cultural tourism vs. Nature tourism',
    'Wants to learn a new language vs. Wants to learn new food recipes',
    'Adventurous destination vs. Relaxing beach destination',
    'Travel often vs. Prefer staying local',
    'Would love to work abroad vs. Prefer to stay in hometown',
  ],
  'Conversation Style and Humor': [
    'Sarcastic vs. Straightforward',
    'Loves dad jokes vs. Dark humor',
    'Tells long stories vs. Keeps it short',
    'Love puns vs. Find puns annoying',
    'Philosophical vs. Casual talker',
    'Talks about feelings vs. Keeps emotions inside',
    'Playful teasing vs. Serious chat',
    'Laughs at anything vs. Hard to make laugh',
    'Love debates vs. Avoids arguments',
    'Loves to gossip vs. Keeps secrets',
  ],
  'Mindset and Lifestyle': [
    'Minimalist vs. Lover of collections',
    'Yoga/meditation vs. Gym enthusiast',
    'Early riser vs. Late-night thinker',
    'Planner vs. Go with the flow',
    'Has a routine vs. Lives spontaneously',
    'Sleep is sacred vs. Can function on little sleep',
    'Dreamer vs. Doer',
    'Workaholic vs. Work to live',
    'Productivity tools lover vs. Keeps it simple',
    'Journaling vs. Digital planner',
  ],
  'Random Fun Cards': [
    'Would rather live in the past vs. Would rather live in the future',
    'Owns a pet vs. Loves animals but doesn\'t own one',
    'Into conspiracy theories vs. Skeptical of all theories',
    'Would survive in a zombie apocalypse vs. Would probably be the first to go',
    'Has a secret talent vs. Has no secret talents',
    'Into astrology vs. Doesn\'t believe in it',
    'Wants a big family vs. Prefers a small family',
    'Introverts with extrovert friends vs. Extroverts with introvert friends',
    'Has an embarrassing childhood story vs. Keeps that info hidden',
    'Believes in ghosts vs. Doesn\'t believe in them',
  ],
};